ModuleName DEFINITIONS ::=
BEGIN


From ::= SEQUENCE {
	age Age,
	number Number,
	gorce SEQUENCE OF {
		math Scores,
		engligh Scores,
		chinese Scores,
		normalGrades SEQUENCE OF {
			math Scores,
			engligh Scores,
			chinese Scores
		}
		Scores ::= INTEGER
		Age ::= INTEGER
		Number ::= INTEGER
	}
}
END